"""Typed Web capability services and adapters."""

from mishkan.web.models import (
    CacheDisposition,
    CitationEvidence,
    CrawlPage,
    CrawlRequest,
    CrawlResult,
    ExtractionRequest,
    ExtractionResult,
    FetchRequest,
    FetchResult,
    HttpRequest,
    HttpResult,
    MapRequest,
    MapResult,
    RedirectEvidence,
    RedirectPolicy,
    RouteStatus,
    SearchHit,
    SearchRequest,
    SearchResponse,
    SearchRoute,
    SourceSpan,
    WebOperationContext,
)

__all__ = [
    "CacheDisposition",
    "CitationEvidence",
    "CrawlPage",
    "CrawlRequest",
    "CrawlResult",
    "ExtractionRequest",
    "ExtractionResult",
    "FetchRequest",
    "FetchResult",
    "HttpRequest",
    "HttpResult",
    "MapRequest",
    "MapResult",
    "RedirectEvidence",
    "RedirectPolicy",
    "RouteStatus",
    "SearchHit",
    "SearchRequest",
    "SearchResponse",
    "SearchRoute",
    "SourceSpan",
    "WebOperationContext",
]
